name: NoDamage
version: ${project.version}
main: minecraftplugin.nodamage.NoDamage
commands:
  settimeout:
    description: This is a demo command.
    usage: /settimeout
    permission: <NoDamage>.basic
    default: op
    permission-message: You don't have permissions
