name: NoDamage
version: ${project.version}
main: minecraftplugin.nodamage.NoDamage
commands:
  basic:
    description: This is a demo command.
    usage: /basic
    permission: <NoDamage>.basic
    permission-message: You don't have
